name = "burkeruder-ai"
pages_build_output_dir = "out"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "burkeruder-crew"
database_id = "991d2307-7c80-4e55-9c00-e3f7ea4ca98f"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "burkeruder-crew-photos"

[[services]]
binding = "MAILER"
service = "burkeruder-mailer"

[ai]
binding = "AI"
